services:
  test-java17-vscode:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3100:3100
      - 3101:3101
      - 3102:3102
    networks:
      - test-network
    working_dir: /code,
    volumes:
      # 代码库
      - /home/zheng/java17:/code
      # 共享m2仓库，不用每次开启container都要重新下载
      - /home/zheng/.m2:/root/.m2
      # 共享git credentials
      - /home/zheng/.ssh:/root/.ssh

networks:
  test-network:
    external: true
