services:
  test-java17-vscode:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3100:3100
      - 3101:3101
      - 3102:3102
    networks:
      - test-network
    working_dir: /code,
    volumes:
      - /home/zheng/java17:/code
      - /home/zheng/.m2:/home/vscode/.m2

networks:
  test-network:
    external: true
