services:
  test-java17:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3100:3100
      - 3101:3101
      - 3102:3102
    networks:
      - test-network
    working_dir: /code,
    volumes:
      # codebase
      - /home/zheng/java17:/code
      # m2 repository, so that you don't have to download the dependencies everytime you open the container
      - /home/zheng/.m2:/root/.m2
      # share git credentials
      - /home/zheng/.ssh:/root/.ssh

networks:
  test-network:
    external: true
